export interface Order {
  id: string
  created_at: string
  shopify_order_id: number
  shopify_store_id: string
  order_number: string
  customer_email?: string
  customer_first_name?: string
  customer_last_name?: string
  total_price: number
  subtotal_price: number
  total_tax: number
  currency: string
  financial_status: string
  fulfillment_status: string
  order_status: string
  shipping_address?: any
  billing_address?: any
  tags?: string
  note?: string
  processed_at?: string
  cancelled_at?: string
  cancelled_reason?: string
  last_synced_at?: string
  sync_status: 'synced' | 'pending' | 'error'
}

export interface OrderItem {
  id: string
  created_at: string
  order_id: string
  shopify_line_item_id: number
  product_id?: string
  shopify_product_id?: number
  shopify_variant_id?: number
  sku?: string
  title: string
  variant_title?: string
  quantity: number
  price: number
  total_discount: number
  fulfillment_status: string
  requires_shipping: boolean
  taxable: boolean
  gift_card: boolean
}

export interface ShopifyOrder {
  id: number
  email?: string
  closed_at?: string
  created_at: string
  updated_at: string
  number: number
  note?: string
  token: string
  gateway?: string
  test: boolean
  total_price: string
  subtotal_price: string
  total_weight: number
  total_tax: string
  taxes_included: boolean
  currency: string
  financial_status: string
  confirmed: boolean
  total_discounts: string
  name: string
  processed_at?: string
  cancelled_at?: string
  cancel_reason?: string
  total_price_usd: string
  user_id?: number
  location_id?: number
  source_identifier?: string
  source_url?: string
  device_id?: number
  phone?: string
  customer_locale?: string
  app_id?: number
  browser_ip?: string
  landing_site?: string
  landing_site_ref?: string
  referring_site?: string
  marketing_attribution_attribution?: string
  marketing_attribution_attribution_1?: string
  marketing_attribution_attribution_2?: string
  marketing_attribution_attribution_3?: string
  marketing_attribution_attribution_4?: string
  marketing_attribution_attribution_5?: string
  marketing_attribution_attribution_6?: string
  marketing_attribution_attribution_7?: string
  marketing_attribution_attribution_8?: string
  marketing_attribution_attribution_9?: string
  marketing_attribution_attribution_10?: string
  marketing_attribution_attribution_11?: string
  marketing_attribution_attribution_12?: string
  marketing_attribution_attribution_13?: string
  marketing_attribution_attribution_14?: string
  marketing_attribution_attribution_15?: string
  marketing_attribution_attribution_16?: string
  marketing_attribution_attribution_17?: string
  marketing_attribution_attribution_18?: string
  marketing_attribution_attribution_19?: string
  marketing_attribution_attribution_20?: string
  marketing_attribution_attribution_21?: string
  marketing_attribution_attribution_22?: string
  marketing_attribution_attribution_23?: string
  marketing_attribution_attribution_24?: string
  marketing_attribution_attribution_25?: string
  marketing_attribution_attribution_26?: string
  marketing_attribution_attribution_27?: string
  marketing_attribution_attribution_28?: string
  marketing_attribution_attribution_29?: string
  marketing_attribution_attribution_30?: string
  marketing_attribution_attribution_31?: string
  marketing_attribution_attribution_32?: string
  marketing_attribution_attribution_33?: string
  marketing_attribution_attribution_34?: string
  marketing_attribution_attribution_35?: string
  marketing_attribution_attribution_36?: string
  marketing_attribution_attribution_37?: string
  marketing_attribution_attribution_38?: string
  marketing_attribution_attribution_39?: string
  marketing_attribution_attribution_40?: string
  marketing_attribution_attribution_41?: string
  marketing_attribution_attribution_42?: string
  marketing_attribution_attribution_43?: string
  marketing_attribution_attribution_44?: string
  marketing_attribution_attribution_45?: string
  marketing_attribution_attribution_46?: string
  marketing_attribution_attribution_47?: string
  marketing_attribution_attribution_48?: string
  marketing_attribution_attribution_49?: string
  marketing_attribution_attribution_50?: string
  marketing_attribution_attribution_51?: string
  marketing_attribution_attribution_52?: string
  marketing_attribution_attribution_53?: string
  marketing_attribution_attribution_54?: string
  marketing_attribution_attribution_55?: string
  marketing_attribution_attribution_56?: string
  marketing_attribution_attribution_57?: string
  marketing_attribution_attribution_58?: string
  marketing_attribution_attribution_59?: string
  marketing_attribution_attribution_60?: string
  marketing_attribution_attribution_61?: string
  marketing_attribution_attribution_62?: string
  marketing_attribution_attribution_63?: string
  marketing_attribution_attribution_64?: string
  marketing_attribution_attribution_65?: string
  marketing_attribution_attribution_66?: string
  marketing_attribution_attribution_67?: string
  marketing_attribution_attribution_68?: string
  marketing_attribution_attribution_69?: string
  marketing_attribution_attribution_70?: string
  marketing_attribution_attribution_71?: string
  marketing_attribution_attribution_72?: string
  marketing_attribution_attribution_73?: string
  marketing_attribution_attribution_74?: string
  marketing_attribution_attribution_75?: string
  marketing_attribution_attribution_76?: string
  marketing_attribution_attribution_77?: string
  marketing_attribution_attribution_78?: string
  marketing_attribution_attribution_79?: string
  marketing_attribution_attribution_80?: string
  marketing_attribution_attribution_81?: string
  marketing_attribution_attribution_82?: string
  marketing_attribution_attribution_83?: string
  marketing_attribution_attribution_84?: string
  marketing_attribution_attribution_85?: string
  marketing_attribution_attribution_86?: string
  marketing_attribution_attribution_87?: string
  marketing_attribution_attribution_88?: string
  marketing_attribution_attribution_89?: string
  marketing_attribution_attribution_90?: string
  marketing_attribution_attribution_91?: string
  marketing_attribution_attribution_92?: string
  marketing_attribution_attribution_93?: string
  marketing_attribution_attribution_94?: string
  marketing_attribution_attribution_95?: string
  marketing_attribution_attribution_96?: string
  marketing_attribution_attribution_97?: string
  marketing_attribution_attribution_98?: string
  marketing_attribution_attribution_99?: string
  marketing_attribution_attribution_100?: string
  order_number: string
  shipping_lines: any[]
  billing_address?: any
  shipping_address?: any
  fulfillments: any[]
  client_details?: any
  line_items: ShopifyOrderItem[]
  payment_details?: any
  refunds: any[]
  customer?: any
  tags: string
  note_attributes: any[]
  properties: any[]
  total_discounts: string
  total_line_items_price: string
  total_outstanding: string
  total_tip_received: string
  original_total_duties_set: string
  current_total_duties_set: string
  admin_graphql_api_id: string
  shipping_lines: any[]
  discount_codes: any[]
  discount_applications: any[]
  customer_locale?: string
  presentment_currency?: string
  total_price_set?: any
  subtotal_price_set?: any
  total_shipping_price_set?: any
  total_tax_set?: any
  total_discounts_set?: any
  total_line_items_price_set?: any
  total_outstanding_set?: any
  total_tip_received_set?: any
  total_duties_set?: any
  current_total_duties_set?: any
  total_price_usd_set?: any
  subtotal_price_usd_set?: any
  total_shipping_price_usd_set?: any
  total_tax_usd_set?: any
  total_discounts_usd_set?: any
  total_line_items_price_usd_set?: any
  total_outstanding_usd_set?: any
  total_tip_received_usd_set?: any
  total_duties_usd_set?: any
  current_total_duties_usd_set?: any
}

export interface ShopifyOrderItem {
  id: number
  variant_id: number
  title: string
  quantity: number
  sku: string
  variant_title?: string
  vendor?: string
  fulfillment_service: string
  product_id: number
  requires_shipping: boolean
  taxable: boolean
  gift_card: boolean
  name: string
  variant_inventory_management: string
  properties: any[]
  product_exists: boolean
  fulfillable_quantity: number
  grams: number
  price: string
  total_discount: string
  fulfillment_status?: string
  price_set: any
  total_discount_set: any
  discount_allocations: any[]
  duties: any[]
  admin_graphql_api_id: string
  tax_lines: any[]
}

export interface SyncResult {
  success: boolean
  message: string
  synced_orders?: number
  synced_products?: number
  errors?: string[]
} 